"""Prompt templates for the three LLM agents (preferences, drafting,
refinement). Kept as compact as possible to respect the 8000 tok/min
Groq budget: no filler, no repeated context across calls.
"""
import json
from typing import Dict, List, Optional

import config

# ---------------------------------------------------------------------------
# Phase 1 - preference parsing
# ---------------------------------------------------------------------------

_PREFERENCE_JSON_EXAMPLE = {
    "workers": [
        {
            "id": 0,
            "preferred_shifts": ["morning"],
            "avoid_shifts": ["night"],
            "max_consecutive_nights": 2,
            "weekend_preference": "neutral",
            "holiday_tolerance": 0.3,
        }
    ]
}


def preference_prompt(raw_preferences: str, worker_ids: List[int]) -> str:
    return (
        "Extract structured shift preferences from the text below into JSON.\n"
        f"Worker ids in scope: {worker_ids}. Every id must appear exactly once "
        "in the output, even if the text says nothing about them (use neutral "
        "defaults: preferred_shifts=[], avoid_shifts=[], max_consecutive_nights=2, "
        "weekend_preference='neutral', holiday_tolerance=0.5).\n"
        "shifts are one of: morning, afternoon, night.\n"
        "weekend_preference is one of: prefer, avoid, neutral.\n"
        "holiday_tolerance is a float 0-1 (0=wants to avoid holidays entirely, "
        "1=fully fine working holidays).\n\n"
        f"Output schema (JSON only, no prose, no markdown fences):\n"
        f"{json.dumps(_PREFERENCE_JSON_EXAMPLE, indent=2)}\n\n"
        f"Worker preferences (natural language):\n\"\"\"\n{raw_preferences}\n\"\"\"\n"
    )


# ---------------------------------------------------------------------------
# Phase 2 - drafting. The hard-constraint template below MUST be reproduced
# identically by the LLM; only the objective (soft constraints) weights may
# be adapted from preferences. This mirrors the professor's requirement that
# the LLM write the code, guided closely enough to avoid constraint errors.
#
# The input preamble (num_workers, worker_roles, preferences, ...) is built
# deterministically in Python (build_preamble), NOT generated by the LLM:
# asking the model to re-type a ~20-worker preferences dict verbatim wastes
# completion tokens on pure data transcription (scaling with worker count)
# and was the direct cause of a real truncated-script failure on Case B
# (20 workers) -- the model ran out of its token budget mid-transcription
# and never reached the actual solver call. The LLM now only writes the
# CONTINUATION (the part starting at `model = cp_model.CpModel()`), which
# is what actually needs its "reasoning" per the assignment brief.
# ---------------------------------------------------------------------------

# Separates the deterministic preamble from the LLM-written continuation in
# the final assembled script -- purely a human-readable marker (a comment),
# harmless to leave in the runnable file.
PREAMBLE_LOGIC_MARKER = "# ===== LLM-generated logic below ====="


def build_preamble(workers: List[Dict], case_type: str, parsed_preferences: Dict) -> str:
    """Deterministically builds the input-variable block every generated
    script needs (imports + num_workers/case_type/worker_roles/weekend_days/
    holidays/preferences). Never touched by the LLM, so it's always correct."""
    worker_roles = {w["id"]: w["role"] for w in workers}
    preferences_by_id = {p["id"]: p for p in parsed_preferences.get("workers", [])}
    return (
        "from ortools.sat.python import cp_model\n"
        "import json\n\n"
        f"num_workers = {len(workers)}\n"
        f"case_type = \"{case_type}\"\n"
        # NOTE: repr(), not json.dumps() -- these lines are embedded as
        # literal Python source (not re-parsed via json.loads), and
        # json.dumps stringifies dict keys ("0" instead of 0), which would
        # make every `preferences[w]` / `worker_roles[w]` lookup raise
        # KeyError since w is an int.
        f"worker_roles = {worker_roles!r}\n"
        f"weekend_days = {config.WEEKEND_DAYS}\n"
        f"holidays = {config.HOLIDAYS}\n"
        f"preferences = {preferences_by_id!r}\n"
    )


DRAFTING_LOGIC_TEMPLATE = '''model = cp_model.CpModel()

# Variables: x[w][d][s] = 1 if worker w works day d (0..30) shift s
# (0=morning, 1=afternoon, 2=night)
x = {}
for w in range(num_workers):
    x[w] = {}
    for d in range(31):
        x[w][d] = {}
        for s in range(3):
            x[w][d][s] = model.NewBoolVar(f'x_{w}_{d}_{s}')

# HARD CONSTRAINT 1: at most one shift per day
for w in range(num_workers):
    for d in range(31):
        model.Add(sum(x[w][d][s] for s in range(3)) <= 1)

# HARD CONSTRAINT 2: no back-to-back night -> next-day morning
for w in range(num_workers):
    for d in range(30):
        model.Add(x[w][d][2] + x[w][d + 1][0] <= 1)

# HARD CONSTRAINT 3: 2 full days off after a night shift
for w in range(num_workers):
    for d in range(29):
        for offset in [1, 2]:
            model.Add(
                x[w][d][2] + sum(x[w][d + offset][s] for s in range(3)) <= 1
            )

# HARD CONSTRAINT 4: monthly weighted load == 25
for w in range(num_workers):
    model.Add(
        sum(x[w][d][0] + x[w][d][1] + 2 * x[w][d][2] for d in range(31)) == 25
    )

# HARD CONSTRAINT 5: weekly weighted load <= 6 (fixed Mon-Sun windows)
weeks = [(0, 6), (7, 13), (14, 20), (21, 27), (28, 30)]
for w in range(num_workers):
    for start, end in weeks:
        model.Add(
            sum(
                x[w][d][0] + x[w][d][1] + 2 * x[w][d][2]
                for d in range(start, end + 1)
            )
            <= 6
        )

# HARD CONSTRAINT 6: at least one fully free day in the horizon
for w in range(num_workers):
    day_off_vars = []
    for d in range(31):
        day_off = model.NewBoolVar(f'day_off_{w}_{d}')
        model.Add(sum(x[w][d][s] for s in range(3)) == 0).OnlyEnforceIf(day_off)
        day_off_vars.append(day_off)
    model.Add(sum(day_off_vars) >= 1)

# HARD CONSTRAINT 7: minimum coverage per shift
days = range(31)
shifts = range(3)
if case_type == "A":
    for d in days:
        for s in shifts:
            model.Add(sum(x[w][d][s] for w in range(num_workers)) >= 2)
else:  # Case B: >=2 standard + >=1 specialized
    # worker ids 0..12 are standard, 13..19 are specialized (per worker_roles)
    standard_workers = [w for w in range(num_workers) if worker_roles[w] == "standard"]
    specialized_workers = [w for w in range(num_workers) if worker_roles[w] == "specialized"]
    for d in days:
        for s in shifts:
            # At least 2 standard
            model.Add(sum(x[w][d][s] for w in standard_workers) >= 2)
            # At least 1 specialized
            model.Add(sum(x[w][d][s] for w in specialized_workers) >= 1)

# SOFT CONSTRAINTS: preferences, encoded as penalty terms to minimize.
# <<<THE LLM SHOULD ADAPT ONLY THIS SECTION, using the `preferences` dict>>>
objective_terms = []
for w in range(num_workers):
    pref = preferences[w]
    for d in range(31):
        if "night" in pref.get("avoid_shifts", []):
            objective_terms.append(10 * x[w][d][2])
        if "afternoon" in pref.get("avoid_shifts", []):
            objective_terms.append(4 * x[w][d][1])
        if "morning" in pref.get("avoid_shifts", []):
            objective_terms.append(4 * x[w][d][0])
    if pref.get("weekend_preference") == "avoid":
        for d in weekend_days:
            objective_terms.append(3 * sum(x[w][d][s] for s in range(3)))
    holiday_cost = int(round(10 * (1 - pref.get("holiday_tolerance", 0.5))))
    for d in holidays:
        objective_terms.append(holiday_cost * sum(x[w][d][s] for s in range(3)))

model.Minimize(sum(objective_terms))

solver = cp_model.CpSolver()
solver.parameters.max_time_in_seconds = 60
solver.parameters.num_search_workers = 8
status = solver.Solve(model)

result = {"status": solver.StatusName(status)}
if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
    schedule = {}
    for d in range(31):
        schedule[d] = {}
        for s in range(3):
            schedule[d][s] = [w for w in range(num_workers) if solver.Value(x[w][d][s])]
    result["schedule"] = schedule
    result["objective_value"] = solver.ObjectiveValue()
else:
    result["schedule"] = None

print(json.dumps(result))
'''


def drafting_prompt(
    workers: List[Dict],
    case_type: str,
    parsed_preferences: Dict,
) -> str:
    preamble = build_preamble(workers, case_type, parsed_preferences)
    return (
        "The variables below are ALREADY DEFINED in the runtime your code "
        "runs in -- do NOT redeclare them, do NOT re-import anything, and "
        "do NOT print/repeat them; your answer is appended directly after "
        "this block and only needs to USE these names:\n\n"
        f"```python\n{preamble}```\n\n"
        "Write the CONTINUATION of this script, starting from "
        "`model = cp_model.CpModel()`, that builds and solves the hospital "
        "shift-scheduling CP-SAT model below, then prints the JSON result "
        "to stdout via `print(json.dumps(result))`. Reproduce every HARD "
        "CONSTRAINT exactly as given (do not rename, reorder, weaken, or "
        "drop any of them). You may only adapt the SOFT CONSTRAINTS "
        "section, using the `preferences` variable already defined above.\n\n"
        "TEMPLATE (hard constraints must stay identical, adapt only the "
        "soft-constraint objective_terms section using `preferences`):\n"
        f"```python\n{DRAFTING_LOGIC_TEMPLATE}\n```\n\n"
        "Return ONLY the Python source code starting from "
        "`model = cp_model.CpModel()` -- no imports, no variable "
        "redeclarations, no prose, no markdown fences."
    )


# ---------------------------------------------------------------------------
# Phase 4 - refinement
# ---------------------------------------------------------------------------


def refinement_prompt(
    previous_code: str,
    hard_errors: List[str],
    fairness_scores: Dict,
    least_satisfied: List[int],
    code_error: Optional[str] = None,
) -> str:
    parts = [
        "The previous script CONTINUATION below (same runtime/variables as "
        "before: num_workers, case_type, worker_roles, weekend_days, "
        "holidays, preferences are already defined -- do not redeclare or "
        "re-import anything) needs a fix. Return the FULL corrected "
        "continuation, starting from `model = cp_model.CpModel()` and "
        "ending with `print(json.dumps(result))` (same rules as before: "
        "hard constraints identical, no prose, no markdown fences).\n"
    ]
    if code_error:
        parts.append(f"SYNTAX/RUNTIME ERROR to fix:\n{code_error}\n")
    if hard_errors:
        parts.append(
            "HARD CONSTRAINT VIOLATIONS to fix (the generated code did not "
            "faithfully encode the template, or the model was mis-parameterized):\n"
            + "\n".join(f"- {e}" for e in hard_errors)
            + "\n"
        )
    if fairness_scores:
        worst = ", ".join(str(w) for w in least_satisfied)
        parts.append(
            f"FAIRNESS: least-satisfied worker(s): {worst}. "
            f"Current scores: {json.dumps(fairness_scores)}. "
            "Adjust the soft-constraint weights in objective_terms so these "
            "workers' preferences are weighted more heavily, WITHOUT "
            "changing any hard constraint or the monthly/weekly totals.\n"
        )
    parts.append(f"PREVIOUS CONTINUATION:\n```python\n{previous_code}\n```")
    return "\n".join(parts)
